### ISSUE TITLE
Should use fork to better view commits

### ISSUE THREAD

**Issue by Lemocuber** [LittleDuck-LD/EMBrawl-51#1]
Since this project, as stated in the readme, is a fork from BSDS; why is it uploaded as a new repo?
This breaks the whole commit history thing :(

**Comment by LittleDuck-LD** [comment]
你看提交历史有什么用
还有其他用bsds改的私服都是这么写的
比如lsbs-v49
另外能不能不要一看到我就开喷

**Comment by Lemocuber** [comment]
🥺
